services:
  chimerabot:
    container_name: chimerabot
    image: chimerabot/chimerabot:latest
    # build: # Uncomment this build section and comment image to build ChimeraBot locally
    #   context: .
    #   dockerfile: Dockerfile
    volumes:
      - ./conf:/home/chimerabot/conf
      - ./conf/connectors:/home/chimerabot/conf/connectors
      - ./conf/strategies:/home/chimerabot/conf/strategies
      - ./conf/controllers:/home/chimerabot/conf/controllers
      - ./conf/scripts:/home/chimerabot/conf/scripts
      - ./logs:/home/chimerabot/logs
      - ./data:/home/chimerabot/data
      - ./certs:/home/chimerabot/certs
      - ./scripts:/home/chimerabot/scripts
      - ./controllers:/home/chimerabot/controllers
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    tty: true
    stdin_open: true
    network_mode: host
  #  environment:
  #    - CONFIG_PASSWORD=admin
  #    - CONFIG_FILE_NAME=v2_with_controllers.py
  #    - SCRIPT_CONFIG=conf_v2_with_controllers.yml

  gateway:
   profiles: ["gateway"]
   restart: always
   container_name: chimerabot-gateway
   image: chimerabot/gateway:latest
   ports:
     - "15888:15888"
   volumes:
     - "./gateway-files/conf:/home/gateway/conf"
     - "./gateway-files/logs:/home/gateway/logs"
     - "./certs:/home/gateway/certs"
   environment:
     - GATEWAY_PASSPHRASE=admin
     - DEV=true
